[
    {
        "repo_name": "pyca/cryptography",
        "CVE_ID": "CVE-2018-10903",
        "Problem_Type": "CWE-20",
        "Description": "A flaw was found in python-cryptography versions between >=1.9.0 and <2.3. The finalize_with_tag API did not enforce a minimum tag length. If a user did not validate the input length prior to passing it to finalize_with_tag an attacker could craft an invalid payload with a shortened tag (e.g. 1 byte) such that they would have a 1 in 256 chance of passing the MAC check. GCM tag forgeries can cause key leakage.",
        "URL": "https://github.com/pyca/cryptography/pull/4342/commits/688e0f673bfbf43fa898994326c6877f00ab19ef",
        "Tag": "['Patch', 'Third Party Advisory']",
        "fix_commit_hash": "d4378e42937b56f473ddade2667f919ce32208cb",
        "inducing_commit_hash_pyszz": [],
        "inducing_commit_hash_pd": [],
        "matched": []
    },
    {
        "repo_name": "pyca/cryptography",
        "CVE_ID": "CVE-2020-25659",
        "Problem_Type": "NVD-CWE-Other",
        "Description": "python-cryptography 3.2 is vulnerable to Bleichenbacher timing attacks in the RSA decryption API, via timed processing of valid PKCS#1 v1.5 ciphertext.",
        "URL": "https://github.com/pyca/cryptography/pull/5507/commits/ce1bef6f1ee06ac497ca0c837fbd1c7ef6c2472b",
        "Tag": "['Patch', 'Third Party Advisory']",
        "fix_commit_hash": "58494b41d6ecb0f56b7c5f05d5f5e3ca0320d494",
        "inducing_commit_hash_pyszz": [
            "bc609feef8bfd472bbf3cefad2a18a1761af9751"
        ],
        "inducing_commit_hash_pd": [
            "35a0e8d403fa5faf7a8e958b6cb63e5d90680d46",
            "bc609feef8bfd472bbf3cefad2a18a1761af9751"
        ],
        "matched": [
            "bc609feef8bfd472bbf3cefad2a18a1761af9751"
        ]
    },
    {
        "repo_name": "pyca/cryptography",
        "CVE_ID": "CVE-2023-23931",
        "Problem_Type": "CWE-754",
        "Description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.",
        "URL": "https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3",
        "Tag": "['Patch']",
        "fix_commit_hash": "9fbf84efc861668755ab645530ec7be9cf3c6696",
        "inducing_commit_hash_pyszz": [
            "f90ba1808ee9bd9a13c5673b776484644f29d7ba"
        ],
        "inducing_commit_hash_pd": [
            "f90ba1808ee9bd9a13c5673b776484644f29d7ba"
        ],
        "matched": [
            "f90ba1808ee9bd9a13c5673b776484644f29d7ba"
        ]
    },
    {
        "repo_name": "pyca/cryptography",
        "CVE_ID": "CVE-2023-38325",
        "Problem_Type": "CWE-295",
        "Description": "The cryptography package before 41.0.2 for Python mishandles SSH certificates that have critical options.",
        "URL": "https://github.com/pyca/cryptography/pull/9208",
        "Tag": "['Patch', 'Vendor Advisory']",
        "fix_commit_hash": "1ca7adc97b76a9dfbd3d850628b613eb93b78fc3",
        "inducing_commit_hash_pyszz": [
            "1b4ad81ff3004b436e627b9e248905113b9cc4a1"
        ],
        "inducing_commit_hash_pd": [
            "1b4ad81ff3004b436e627b9e248905113b9cc4a1",
            "aca8de845e751dd45fe4e48f8492f357d34d1861"
        ],
        "matched": [
            "1b4ad81ff3004b436e627b9e248905113b9cc4a1"
        ]
    },
    {
        "repo_name": "pyca/cryptography",
        "CVE_ID": "CVE-2023-49083",
        "Problem_Type": "CWE-476",
        "Description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.",
        "URL": "https://github.com/pyca/cryptography/pull/9926",
        "Tag": "['Issue Tracking', 'Patch']",
        "fix_commit_hash": "1e7b4d074e14c4e694d3ce69ad6754a6039fd6ff",
        "inducing_commit_hash_pyszz": [
            "c898871daac710f00154cb7041e3876fc66c1ef5"
        ],
        "inducing_commit_hash_pd": [
            "c898871daac710f00154cb7041e3876fc66c1ef5"
        ],
        "matched": [
            "c898871daac710f00154cb7041e3876fc66c1ef5"
        ]
    }
]