[{"repo_name": "geopython/pywps", "CVE_ID": "CVE-2021-39371", "Problem_Type": "CWE-611", "Description": "An XML external entity (XXE) injection in PyWPS before 4.4.5 allows an attacker to view files on the application server filesystem by assigning a path to the entity. OWSLib 0.24.1 may also be affected.", "URL": "https://github.com/geopython/pywps/pull/616", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "7d6b26a2e931df2feca0b7fb24f4d01610825aee", "inducing_commit_hash_pyszz": []}]