[{"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2021-22563", "Problem_Type": "CWE-125", "Description": "Invalid JPEG XL images using libjxl can cause an out of bounds access on a std::vector<std::vector<T>> when rendering splines. The OOB read access can either lead to a segfault, or rendering splines based on other process memory. It is recommended to upgrade past 0.6.0 or patch with https://github.com/libjxl/libjxl/pull/757", "URL": "https://github.com/libjxl/libjxl/pull/757", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "0eff04c3a04e72e78d35f0965f17f54a98d61830", "inducing_commit_hash_pyszz": ["9d03bfe8111f49210e2d096688dd4db303654270"]}, {"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2021-22564", "Problem_Type": "CWE-787", "Description": "For certain valid JPEG XL images with a size slightly larger than an integer number of groups (256x256 pixels) when processing the groups out of order the decoder can perform an out of bounds copy of image pixels from an image buffer in the heap to another. This copy can occur when processing the right or bottom edges of the image, but only when groups are processed in certain order. Groups can be processed out of order in multi-threaded decoding environments with heavy thread load but also with images that contain the groups in an arbitrary order in the file. It is recommended to upgrade past 0.6.0 or patch with https://github.com/libjxl/libjxl/pull/775", "URL": "https://github.com/libjxl/libjxl/pull/775", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "e6497057899269bb40f54a26729826a55d857fd7", "inducing_commit_hash_pyszz": ["62d73ec29aa111e9aec28cd761be4fca6e50b5d0"]}, {"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2021-36692", "Problem_Type": "CWE-369", "Description": "libjxl v0.3.7 is affected by a Divide By Zero in issue in lib/extras/codec_apng.cc jxl::DecodeImageAPNG(). When encoding a malicous APNG file using cjxl, an attacker can trigger a denial of service.", "URL": "https://github.com/libjxl/libjxl/pull/313", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "7dfa400ded53919d986c5d3d23446a09e0cf481b", "inducing_commit_hash_pyszz": []}, {"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2021-45928", "Problem_Type": "CWE-787", "Description": "libjxl b02d6b9, as used in libvips 8.11 through 8.11.2 and other products, has an out-of-bounds write in jxl::ModularFrameDecoder::DecodeGroup (called from jxl::FrameDecoder::ProcessACGroup and jxl::ThreadPool::RunCallState<jxl::FrameDecoder::ProcessSections).", "URL": "https://github.com/libjxl/libjxl/pull/365", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "1c05e110d69b457696366fb4e762057b6855349b", "inducing_commit_hash_pyszz": ["48e2a0ba25a7bac9ec510c48e322e5199de0583e"]}, {"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2023-0645", "Problem_Type": "CWE-125", "Description": "An out of bounds read exists in libjxl. An attacker using a specifically crafted file could cause an out of bounds read in the exif handler. We recommend upgrading to version 0.8.1 or past commit\u00c2\u00a0 https://github.com/libjxl/libjxl/pull/2101/commits/d95b050c1822a5b1ede9e0dc937e43fca1b10159 https://github.com/libjxl/libjxl/pull/2101/commits/d95b050c1822a5b1ede9e0dc937e43fca1b10159 ", "URL": "https://github.com/libjxl/libjxl/pull/2101/commits/d95b050c1822a5b1ede9e0dc937e43fca1b10159", "Tag": "['Patch']", "fix_commit_hash": "a7c8428b61299f3b055cbbdbba3fbcd8cb38d084", "inducing_commit_hash_pyszz": []}, {"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2023-0645", "Problem_Type": "CWE-125", "Description": "An out of bounds read exists in libjxl. An attacker using a specifically crafted file could cause an out of bounds read in the exif handler. We recommend upgrading to version 0.8.1 or past commit\u00c2\u00a0 https://github.com/libjxl/libjxl/pull/2101/commits/d95b050c1822a5b1ede9e0dc937e43fca1b10159 https://github.com/libjxl/libjxl/pull/2101/commits/d95b050c1822a5b1ede9e0dc937e43fca1b10159 ", "URL": "https://github.com/libjxl/libjxl/pull/2101", "Tag": "['Issue Tracking', 'Patch']", "fix_commit_hash": "a7c8428b61299f3b055cbbdbba3fbcd8cb38d084", "inducing_commit_hash_pyszz": []}, {"repo_name": "libjxl/libjxl", "CVE_ID": "CVE-2023-35790", "Problem_Type": "CWE-191", "Description": "An issue was discovered in dec_patch_dictionary.cc in libjxl before 0.8.2. An integer underflow in patch decoding can lead to a denial of service, such as an infinite loop.", "URL": "https://github.com/libjxl/libjxl/pull/2551", "Tag": "['Patch']", "fix_commit_hash": "d4e67a644d8babe7cb68de122d8b5ccb2ad8f226", "inducing_commit_hash_pyszz": []}]