[
    {
        "repo_name": "geopython/pywps",
        "CVE_ID": "CVE-2021-39371",
        "Problem_Type": "CWE-611",
        "Description": "An XML external entity (XXE) injection in PyWPS before 4.4.5 allows an attacker to view files on the application server filesystem by assigning a path to the entity. OWSLib 0.24.1 may also be affected.",
        "URL": "https://github.com/geopython/pywps/pull/616",
        "Tag": "['Patch', 'Third Party Advisory']"
    }
]