[
    {
        "repo_name": "keylime/keylime",
        "CVE_ID": "CVE-2022-3500",
        "Problem_Type": "CWE-248",
        "Description": "A vulnerability was found in keylime. This security issue happens in some circumstances, due to some improperly handled exceptions, there exists the possibility that a rogue agent could create errors on the verifier that stopped attestation attempts for that host leaving it in an attested state but not verifying that anymore.",
        "URL": "https://github.com/keylime/keylime/pull/1128",
        "Tag": "['Issue Tracking', 'Patch', 'Third Party Advisory']",
        "fix_commit_hash": "f969d397f92962b553f8c5bcbbeeb3bbdeca9456"
    },
    {
        "repo_name": "keylime/keylime",
        "CVE_ID": "CVE-2023-38200",
        "Problem_Type": "CWE-834",
        "Description": "A flaw was found in Keylime. Due to their blocking nature, the Keylime registrar is subject to a remote denial of service against its SSL connections. This flaw allows an attacker to exhaust all available connections.",
        "URL": "https://github.com/keylime/keylime/pull/1421",
        "Tag": "['Patch']",
        "fix_commit_hash": "c68d8f0b7ea549c12b6956ab0f3c28ae0360ae17"
    }
]