[
    {
        "repo_name": "numpy/numpy",
        "CVE_ID": "CVE-2014-1859",
        "Problem_Type": "CWE-59",
        "Description": "(1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file.",
        "URL": "https://github.com/numpy/numpy/pull/4262",
        "Tag": "['Issue Tracking', 'Patch', 'Third Party Advisory']",
        "fix_commit_hash": "c7a30d538ba4c984d6f97b613486a3738b2c7922"
    }
]